#! /bin/sh -e

### BEGIN INIT INFO
# Provides:          libnss-ldap
# Required-Start:    
# Required-Stop:     mountall.sh
# Default-Start:     
# Default-Stop:      0 1 6
# Short-Description: Updates /etc/ldap.conf
# Description:       Updates nss_initgroups_ignoreusers based on
#                    nss_initgroups_minimum_uid
### END INIT INFO

PATH="/sbin:/bin:/usr/sbin:/usr/bin"
. /lib/lsb/init-functions

case "$1" in
	start)
		;;
	restart|force-reload|stop)
		log_action_begin_msg "Running nssldap-update-ignoreusers"
		if nssldap-update-ignoreusers ; then
			log_action_end_msg 0
		else
			log_action_end_msg 1
			exit 1
		fi
		;;
	*)
		echo "Usage: $0 {start|restart|force-reload|stop}"
		exit 1
	;;
esac
exit 0
