#!/bin/sh
# kFreeBSD does not accept scripts as interpreters, using #!/bin/sh and sourcing.
if [ true != "$INIT_D_SCRIPT_SOURCED" ] ; then
    set "$0" "$@"; INIT_D_SCRIPT_SOURCED=true . /lib/init/init-d-script
fi
### BEGIN INIT INFO
# Provides:          seatd
# Required-Start:    $local_fs $remote_fs
# Required-Stop:     $local_fs $remote_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Seat and session management daemon
### END INIT INFO

# Author: Mark Hindley <mark@hindley.org.uk>

NAME=seatd
DAEMON=/usr/sbin/seatd
START_ARGS="--background --make-pidfile"
