#!/bin/sh
set -e
# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper rm_conffile /etc/apport/blacklist.d/README.blacklist 2.25.0 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apport/blacklist.d/apport 2.25.0 -- "$@"
dpkg-maintscript-helper rm_conffile /etc/apport/native-origins.d/lts-q-backports 2.5.1-0ubuntu8\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init/apport.conf 2.20.6-0ubuntu5\~ -- "$@"
# End automatically added section
