#! /bin/sh
set -e

if [ "$1" = remove ]; then
    # Remove DEP17 M8 protective diversion
    dpkg-divert --quiet --remove --no-rename --divert "/lib/ld-linux-armhf.so.3.usr-is-merged" "/lib/ld-linux-armhf.so.3"
fi

# Automatically added by dh_installdebconf/13.14.1ubuntu5
if [ "$1" = purge ] && [ -e /usr/share/debconf/confmodule ]; then
	. /usr/share/debconf/confmodule
	db_purge
fi
# End automatically added section


exit 0
