#!/bin/sh

set -e

# begin-remove-after: released:forky
# usrmerge transition from netplan.io -> netplan-generator, see https://bugs.debian.org/1060661
if [ "$1" = configure ] || [ "$1" = abort-upgrade ]; then
    dpkg-divert --no-rename --divert /lib/systemd/system-generators/netplan.usr-is-merged --remove /lib/systemd/system-generators/netplan
fi
# end-remove-after

# Calling the generator after installation to mitigate CVE-2022-4968
# We avoid calling the generator if the system doesn't have networkd files to be fixed (LP: #2071333)
if [ "$1" = configure ]; then
    FILES=$(find /run/systemd/network/ -type f -regex ".*-netplan.*\.\(network\|netdev\)" 2>/dev/null || true)
    if [ -n "${FILES}" ]; then
        /usr/libexec/netplan/generate 2>/dev/null || echo "WARNING: Netplan could not re-generate network configuration. Please run 'netplan generate' to see details."
    fi
fi


