#!/bin/sh

set -e

if [ "$1" = "install" ] && [ -n "$2" ] ; then
	[ -f /etc/logrotate.d/rsyslog.disabled ] && mv -f /etc/logrotate.d/rsyslog.disabled /etc/logrotate.d/rsyslog
fi

# Automatically added by dh_installdeb/13.14.1ubuntu5
dpkg-maintscript-helper rm_conffile /etc/default/rsyslog 8.1905.0-4\~ -- "$@"
dpkg-maintscript-helper rm_conffile /etc/init.d/rsyslog 8.2110.0-2\~ -- "$@"
# End automatically added section

