#!/bin/bash

handle_all_ucf_files $PKGDIR $LOCDIR
mv $PKGF $PKGRF
echo "this is a locally changed file" > $LOCF
take_ref
echo "rename_ucf_file"
rename_ucf_file $LOCF $LOCRF
echo "handle_all_ucf_files"
handle_all_ucf_files $PKGDIR $LOCDIR
is_local $LOCRF && check_ucfq_number 1
return $?

