#!/bin/bash

handle_all_ucf_files $PKGDIR $LOCDIR
rm -f $PKGF
echo "this is a locally changed file" > $LOCF
take_ref
export UCF_FORCE_CONFFOLD=1
handle_all_ucf_files $PKGDIR $LOCDIR
is_local $LOCF && check_ucfq_number 0
return $?

