#!/bin/bash

handle_all_ucf_files $PKGDIR $LOCDIR
cp package-changed $PKGRF
rm -f $PKGF
take_ref
echo "rename_ucf_file $LOCF $LOCRF"
rename_ucf_file $LOCF $LOCRF
echo "handle_all_ucf_files $PKGDIR $LOCDIR"
handle_all_ucf_files $PKGDIR $LOCDIR
echo "final check"
is_package $LOCRF $PKGRREF && check_ucfq_number 1
return $?
