#!/bin/bash

handle_all_ucf_files $PKGDIR $LOCDIR
rm -f $PKGF
rm -f $LOCF
take_ref
# the current code causes the deleted/deleted case to emit a ucf prompt
# we can live with that since both choices yield the same result
export UCF_FORCE_CONFFOLD=1
handle_all_ucf_files $PKGDIR $LOCDIR
is_deleted $LOCF && check_ucfq_number 0
return $?

