#!/bin/sh
set -e
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/keyboard-setup.sh" ] ; then
	chmod +x "/etc/init.d/keyboard-setup.sh" >/dev/null || true
fi
# End automatically added section
# Automatically added by dh_installinit/13.11.4
if [ "$1" = "install" ] && [ -n "$2" ] && [ -e "/etc/init.d/console-setup.sh" ] ; then
	chmod +x "/etc/init.d/console-setup.sh" >/dev/null || true
fi
# End automatically added section
